/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Tutorial
 * OpenAPI Tutorial by halhorn
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * タイヤ
 * @export
 * @interface Tire
 */
export interface Tire {
    /**
     * シリーズ
     * @type {string}
     * @memberof Tire
     */
    series: string;
    /**
     * ブランド
     * @type {string}
     * @memberof Tire
     */
    brand: string;
    /**
     * メーカー
     * @type {string}
     * @memberof Tire
     */
    maker: string;
    /**
     * タイプ
     * @type {string}
     * @memberof Tire
     */
    type: string;
    /**
     * カウント
     * @type {number}
     * @memberof Tire
     */
    count: number;
}

export function TireFromJSON(json: any): Tire {
    return TireFromJSONTyped(json, false);
}

export function TireFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tire {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'series': json['series'],
        'brand': json['brand'],
        'maker': json['maker'],
        'type': json['type'],
        'count': json['count'],
    };
}

export function TireToJSON(value?: Tire | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'series': value.series,
        'brand': value.brand,
        'maker': value.maker,
        'type': value.type,
        'count': value.count,
    };
}

