version: "3"

services:
  php:
    container_name: tiretrend_php
    build: ./docker/php
    volumes:
      - ./project:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    networks:
      - tiretrend

  db:
    image: mysql:5.7
    container_name: tiretrend_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 53306:3306
    networks:
      - tiretrend

networks:
  tiretrend:
