openapi: 3.0.0
info:
  title: OpenAPI Tutorial
  description: OpenAPI Tutorial by halhorn
  version: 0.0.0
servers:
  - url: http://localhost:80/api/v1
    description: 開発用
paths:
  /tires:
    get:
      security:
        - bearerAdmin: []
      tags:
        - 'tires'
      summary: タイヤの一覧を取得します。
      description: 詳細内容
      parameters:
        - in: query
          name: periodStart
          schema:
            type: string
          description: 期間(開始) YYYY/MM/DD
          required: false
        - in: query
          name: periodEnd
          schema:
            type: string
          description: 期間(終了) YYYY/MM/DD
          required: false
        - in: query
          name: maker
          schema:
            type: string
          description: メーカー
          required: false
        - in: query
          name: type
          schema:
            type: string
          description: タイプ
          required: false
      responses:
        '200':
          description: タイヤ一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tire'

components:
  schemas:
    tire:
      description: タイヤ
      type: object
      properties:
        series:
          type: string
          description: シリーズ
        brand:
          type: string
          description: ブランド
        maker:
          type: string
          description: メーカー
        type:
          type: string
          description: タイプ
        count:
          type: integer
          description: カウント
      required:
        - series
        - brand
        - maker
        - type
        - count
    GetTireQuery:
      description: GET /trie クエリ
      type: object
      properties:
        periodStart:
          type: string
          description: 期間(開始) YYYY/MM/DD
        periodEnd:
          type: string
          description: 期間(終了) YYYY/MM/DD
        maker:
          type: string
          description: メーカー
        type:
          type: string
          description: タイプ
